project:
  type: website

website:
  title: "GVPT Maths Camp"

  favicon: "/files/img/hex-testudo.png"

  navbar:
    pinned: true
    background: "#3B3C54"
    right:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: content/01-content.qmd
        text: Content

  sidebar:
    - title: "Content"
      style: "docked"
      contents:
        - content/01-content.qmd
        - content/02-content.qmd
        - content/03-content.qmd
        - content/04-content.qmd

format:
  html:
    theme: litera
    css: html/custom.css
    toc: true
    highlight-style: monokai

editor: visual

