---
title: "Schedule"
sidebar: false
toc: false
page-layout: full
---

```{r packages, include = FALSE}
library(tidyverse)
library(kableExtra)
library(fontawesome)
```

```{r, include = FALSE}
schedule <- tibble(
  DATE = c("DAY 1", "DAY 1"),
  SESSION = c("Morning", "Afternoon"),
  TITLE = c("Introduction and set up", "Data Visualisation"),
  CONTENT = c("index.html"),
  EXAMPLE = c(""),
  ASSIGNMENT = c("")
) |> 
  mutate(
    CONTENT = if_else(CONTENT != "", 
                      paste0("<a href=\"http://localhost:3933/content/", CONTENT, "\">", as.character(fa("book")), "</a>"),
                      as.character(fa("book"))),
    EXAMPLE = if_else(EXAMPLE != "",
                      paste0("<a href=\"http://localhost:3933/content/", EXAMPLE, "\">", as.character(fa("gears")), "</a>"),
                      as.character(fa("gears"))),
    ASSIGNMENT = if_else(ASSIGNMENT != "",
                         paste0("<a href=\"http://localhost:3933/content/", ASSIGNMENT, "\">", as.character(fa("pen-ruler")), "</a>"),
                         as.character(fa("pen-ruler")))
  )
```

```{r schedule, echo = FALSE, results = "asis"}
schedule |>
  kbl(escape = FALSE, align = "lllccc") |>
  kable_styling(bootstrap_options = c("hover", "responsive"),
                fixed_thead = T) |> 
  column_spec(1, width = "10%", extra_css = "padding-right: 20px;") |> 
  column_spec(2, width = "10%") |> 
  column_spec(3, width = "60%") |> 
  column_spec(4, width = "10%") |> 
  column_spec(5, width = "10%") |> 
  column_spec(6, width = "10%")
```
