---
title: "GVPT Maths Camp"
subtitle: "Bringing it all together"
format: 
  revealjs:
    slide-number: true
    preview-links: auto
    theme: solarized
    embed-resources: true
execute: 
  echo: true
---

## Learning objectives

1.  Explore an interesting question using the skills you have learnt

2.  Create a script that you can use to explore new data sets in the future

## EXERCISE {background-color="#B56576"}

You are going to present for 5 minutes on a topic of your choice. You will create a set of slides or a 1-2 page document to support this presentation.

## EXERCISE {background-color="#B56576"}

In this presentation, you will need to include the following: 

1.  A plot of a categorical variable in your data set.
2.  A plot of a continuous variable in your data set.
3.  A plot showing the relationship between two continuous variables in your data set.
4.  A plot showing the relationship between a categorical and a continuous variable in your data set.
5.  A description of these relationships in simple, clear language.

